apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secrets.slackWebhookUrl | quote }}